# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: oncall
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MzYwM2ViZmFkNmY5ZjkzZDUxMTMwZmYzOWU2ZmIwMDNhNTc4ZjMxMzZjMGZhN2IzYmNiMjRhZTZlMWNlMzI3ZTc5ZGE0NzBiMjczOTc1NTc5NGVjYjM0YTY5ODJhMTI5MjAxOTRiM2JhN2Q0MmM0MDY3N2UzYTI1N2ZkNGM3MTk=
