package ar.edu.um.isa.oncall.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ContactoDeProveedorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContactoDeProveedorAllPropertiesEquals(ContactoDeProveedor expected, ContactoDeProveedor actual) {
        assertContactoDeProveedorAutoGeneratedPropertiesEquals(expected, actual);
        assertContactoDeProveedorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContactoDeProveedorAllUpdatablePropertiesEquals(ContactoDeProveedor expected, ContactoDeProveedor actual) {
        assertContactoDeProveedorUpdatableFieldsEquals(expected, actual);
        assertContactoDeProveedorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContactoDeProveedorAutoGeneratedPropertiesEquals(ContactoDeProveedor expected, ContactoDeProveedor actual) {
        assertThat(actual)
            .as("Verify ContactoDeProveedor auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContactoDeProveedorUpdatableFieldsEquals(ContactoDeProveedor expected, ContactoDeProveedor actual) {
        assertThat(actual)
            .as("Verify ContactoDeProveedor relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getTelefono()).as("check telefono").isEqualTo(expected.getTelefono()))
            .satisfies(a -> assertThat(a.getRol()).as("check rol").isEqualTo(expected.getRol()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContactoDeProveedorUpdatableRelationshipsEquals(ContactoDeProveedor expected, ContactoDeProveedor actual) {
        assertThat(actual)
            .as("Verify ContactoDeProveedor relationships")
            .satisfies(a -> assertThat(a.getProveedor()).as("check proveedor").isEqualTo(expected.getProveedor()));
    }
}
