package ar.edu.um.isa.oncall.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IncidenteDeProveedorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncidenteDeProveedorAllPropertiesEquals(IncidenteDeProveedor expected, IncidenteDeProveedor actual) {
        assertIncidenteDeProveedorAutoGeneratedPropertiesEquals(expected, actual);
        assertIncidenteDeProveedorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncidenteDeProveedorAllUpdatablePropertiesEquals(IncidenteDeProveedor expected, IncidenteDeProveedor actual) {
        assertIncidenteDeProveedorUpdatableFieldsEquals(expected, actual);
        assertIncidenteDeProveedorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncidenteDeProveedorAutoGeneratedPropertiesEquals(IncidenteDeProveedor expected, IncidenteDeProveedor actual) {
        assertThat(actual)
            .as("Verify IncidenteDeProveedor auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncidenteDeProveedorUpdatableFieldsEquals(IncidenteDeProveedor expected, IncidenteDeProveedor actual) {
        assertThat(actual)
            .as("Verify IncidenteDeProveedor relevant properties")
            .satisfies(a -> assertThat(a.getTicketExterno()).as("check ticketExterno").isEqualTo(expected.getTicketExterno()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a -> assertThat(a.getAbiertoEn()).as("check abiertoEn").isEqualTo(expected.getAbiertoEn()))
            .satisfies(a ->
                assertThat(a.getPrimeraRespuestaEn()).as("check primeraRespuestaEn").isEqualTo(expected.getPrimeraRespuestaEn())
            )
            .satisfies(a -> assertThat(a.getResueltoEn()).as("check resueltoEn").isEqualTo(expected.getResueltoEn()))
            .satisfies(a -> assertThat(a.getCumplioSla()).as("check cumplioSla").isEqualTo(expected.getCumplioSla()))
            .satisfies(a -> assertThat(a.getMotivoRechazo()).as("check motivoRechazo").isEqualTo(expected.getMotivoRechazo()))
            .satisfies(a ->
                assertThat(a.getResponsableResuelto()).as("check responsableResuelto").isEqualTo(expected.getResponsableResuelto())
            )
            .satisfies(a -> assertThat(a.getNivelResuelto()).as("check nivelResuelto").isEqualTo(expected.getNivelResuelto()))
            .satisfies(a -> assertThat(a.getHuboCobertura()).as("check huboCobertura").isEqualTo(expected.getHuboCobertura()))
            .satisfies(a -> assertThat(a.getNotas()).as("check notas").isEqualTo(expected.getNotas()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncidenteDeProveedorUpdatableRelationshipsEquals(IncidenteDeProveedor expected, IncidenteDeProveedor actual) {
        assertThat(actual)
            .as("Verify IncidenteDeProveedor relationships")
            .satisfies(a -> assertThat(a.getIncidente()).as("check incidente").isEqualTo(expected.getIncidente()))
            .satisfies(a ->
                assertThat(a.getServicioDeProveedor()).as("check servicioDeProveedor").isEqualTo(expected.getServicioDeProveedor())
            );
    }
}
