package ar.edu.um.isa.oncall.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProveedorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProveedorAllPropertiesEquals(Proveedor expected, Proveedor actual) {
        assertProveedorAutoGeneratedPropertiesEquals(expected, actual);
        assertProveedorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProveedorAllUpdatablePropertiesEquals(Proveedor expected, Proveedor actual) {
        assertProveedorUpdatableFieldsEquals(expected, actual);
        assertProveedorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProveedorAutoGeneratedPropertiesEquals(Proveedor expected, Proveedor actual) {
        assertThat(actual)
            .as("Verify Proveedor auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProveedorUpdatableFieldsEquals(Proveedor expected, Proveedor actual) {
        assertThat(actual)
            .as("Verify Proveedor relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getTipo()).as("check tipo").isEqualTo(expected.getTipo()))
            .satisfies(a -> assertThat(a.getZonaHoraria()).as("check zonaHoraria").isEqualTo(expected.getZonaHoraria()))
            .satisfies(a -> assertThat(a.getTelefonoContacto()).as("check telefonoContacto").isEqualTo(expected.getTelefonoContacto()))
            .satisfies(a -> assertThat(a.getEmailContacto()).as("check emailContacto").isEqualTo(expected.getEmailContacto()))
            .satisfies(a -> assertThat(a.getUrlSoporte()).as("check urlSoporte").isEqualTo(expected.getUrlSoporte()))
            .satisfies(a -> assertThat(a.getUrlEstado()).as("check urlEstado").isEqualTo(expected.getUrlEstado()))
            .satisfies(a -> assertThat(a.getCobertura()).as("check cobertura").isEqualTo(expected.getCobertura()))
            .satisfies(a ->
                assertThat(a.getSlaRespuestaMinutos()).as("check slaRespuestaMinutos").isEqualTo(expected.getSlaRespuestaMinutos())
            )
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProveedorUpdatableRelationshipsEquals(Proveedor expected, Proveedor actual) {
        // empty method
    }
}
