package ar.edu.um.isa.oncall.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ServicioDeProveedorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicioDeProveedorAllPropertiesEquals(ServicioDeProveedor expected, ServicioDeProveedor actual) {
        assertServicioDeProveedorAutoGeneratedPropertiesEquals(expected, actual);
        assertServicioDeProveedorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicioDeProveedorAllUpdatablePropertiesEquals(ServicioDeProveedor expected, ServicioDeProveedor actual) {
        assertServicioDeProveedorUpdatableFieldsEquals(expected, actual);
        assertServicioDeProveedorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicioDeProveedorAutoGeneratedPropertiesEquals(ServicioDeProveedor expected, ServicioDeProveedor actual) {
        assertThat(actual)
            .as("Verify ServicioDeProveedor auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicioDeProveedorUpdatableFieldsEquals(ServicioDeProveedor expected, ServicioDeProveedor actual) {
        assertThat(actual)
            .as("Verify ServicioDeProveedor relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a ->
                assertThat(a.getIdentificadorExterno()).as("check identificadorExterno").isEqualTo(expected.getIdentificadorExterno())
            )
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a ->
                assertThat(a.getSlaRespuestaMinutos()).as("check slaRespuestaMinutos").isEqualTo(expected.getSlaRespuestaMinutos())
            )
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicioDeProveedorUpdatableRelationshipsEquals(ServicioDeProveedor expected, ServicioDeProveedor actual) {
        assertThat(actual)
            .as("Verify ServicioDeProveedor relationships")
            .satisfies(a -> assertThat(a.getProveedor()).as("check proveedor").isEqualTo(expected.getProveedor()))
            .satisfies(a -> assertThat(a.getServicioInternos()).as("check servicioInternos").isEqualTo(expected.getServicioInternos()));
    }
}
