package ar.edu.um.isa.oncall.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TurnoDeProveedorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTurnoDeProveedorAllPropertiesEquals(TurnoDeProveedor expected, TurnoDeProveedor actual) {
        assertTurnoDeProveedorAutoGeneratedPropertiesEquals(expected, actual);
        assertTurnoDeProveedorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTurnoDeProveedorAllUpdatablePropertiesEquals(TurnoDeProveedor expected, TurnoDeProveedor actual) {
        assertTurnoDeProveedorUpdatableFieldsEquals(expected, actual);
        assertTurnoDeProveedorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTurnoDeProveedorAutoGeneratedPropertiesEquals(TurnoDeProveedor expected, TurnoDeProveedor actual) {
        assertThat(actual)
            .as("Verify TurnoDeProveedor auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTurnoDeProveedorUpdatableFieldsEquals(TurnoDeProveedor expected, TurnoDeProveedor actual) {
        assertThat(actual)
            .as("Verify TurnoDeProveedor relevant properties")
            .satisfies(a -> assertThat(a.getDesde()).as("check desde").isEqualTo(expected.getDesde()))
            .satisfies(a -> assertThat(a.getHasta()).as("check hasta").isEqualTo(expected.getHasta()))
            .satisfies(a -> assertThat(a.getNivel()).as("check nivel").isEqualTo(expected.getNivel()))
            .satisfies(a -> assertThat(a.getEsReemplazo()).as("check esReemplazo").isEqualTo(expected.getEsReemplazo()))
            .satisfies(a -> assertThat(a.getNota()).as("check nota").isEqualTo(expected.getNota()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTurnoDeProveedorUpdatableRelationshipsEquals(TurnoDeProveedor expected, TurnoDeProveedor actual) {
        assertThat(actual)
            .as("Verify TurnoDeProveedor relationships")
            .satisfies(a -> assertThat(a.getContacto()).as("check contacto").isEqualTo(expected.getContacto()));
    }
}
